Added a check for MacOS getopt

diff --git a/f1points b/f1points
--- a/f1points
+++ b/f1points
@@ -44,6 +44,18 @@ exit 0
 
 }
 
+printError() {
+    echo -e "\033[1;31m[ERROR] ${1}\033[0m"
+}
+
+printInfo() {
+    echo -e "\033[1;36m[INFO] ${1}\033[0m"
+}
+
+printOK() {
+    echo -e "\033[1;32m[INFO] ${1}\033[0m"
+}
+
 welcome() {
 
     print \\n
@@ -89,6 +101,11 @@ performSystemCheck() {
 
     # TODO: check for correct shell, jq, possibly getopt etc
 
+    # might need this for compatibilty?
+    #if [ -n "$ZSH_VERSION" ]; then emulate -L ksh; fi
+
+    getoptMacOS
+
 }
 
 #checks whether the utility is correctly configured
@@ -99,7 +116,7 @@ performConfigCheck() {
     echo "NUMBER_OF_PLAYERS -> ${number_of_players}"
 
     if [[ $number_of_players = 0 ]]; then
-        echo "Players are not onfigured. Please load players individually or load initialisation file"
+        printError "Players are not onfigured. Please load players individually or load initialisation file"
         exit 1
     fi
 
@@ -108,7 +125,7 @@ performConfigCheck() {
     echo "DRIVERS_PER_PLAYER -> ${drivers_per_player}"
 
     if [[ $drivers_per_player = 0 ]]; then
-        echo "Drivers per Player is not onfigured. Please configure DRIVERS_PER_PLAYER"
+        printError "Drivers per Player is not onfigured. Please configure DRIVERS_PER_PLAYER"
         exit 1
     fi
 
@@ -133,13 +150,30 @@ configureProperty() {
     readonly returned_key="$(config_check $CONFIG_FILE $key)"
 
     if [[ "${returned_key}" != "${key}" ]]; then
-        echo "Key ${key} not found. Please specify a defined property. available: ${DEFINED_PROPERTIES}"
+        printError "Key ${key} not found. Please specify a defined property. available: ${DEFINED_PROPERTIES}"
+        exit 1
     fi
 
     echo "Configuring ${key} with ${value}"
 
     # TODO: write value to file
 
+}
+
+getoptMacOS() {
+
+    if [[ "$(uname -s)" == 'Darwin' ]]; then
+        if [[ ! -f /usr/local/opt/gnu-getopt/bin/getopt ]]; then
+            if [[ "${SHELL}" == *"bin/fish"* ]]; then
+                printError "The fish shell is not supported. Please use bash or zsh"
+                exit 1
+            fi
+            printError "Please install gnu-getopt via Homebrew with: brew install gnu-getopt"
+            exit 1
+        else
+            export PATH="$(brew --prefix gnu-getopt)/bin:$PATH"
+        fi
+    fi
 }
 
 #script start
